version: '3.1'

services:
  movies-api:
    build: .
    image: 'movies-api'
    ports:
      - '3000:3000'
    depends_on:
      - storage
    volumes:
      - ./:/app
    entrypoint:
      - ./scripts/docker-entrypoint.sh
    env_file: .env

  storage:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - movies-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  movies-data:
