name: Run tests before merge
on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing npm dependencies
        run: npm install

      - name: Running unit tests
        run: npm run test:unit
        env:
          NODE_ENV: "test"
